
spring:
  application:
    name: User-Management
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/luntan?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&connectTimeout=3000&socketTimeout=6000&allowPublicKeyRetrieval=true
      username: root
      password: 126824
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 6000
    username: root
    password: 126824
    url: jdbc:mysql://localhost:3306/luntan?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&connectTimeout=3000&socketTimeout=6000&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 123.56.138.127:8848
      discovery:
        username: nacos
        password: VxykvMqce3
  data:
    redis:
      host: 123.56.138.127
      port: 6379
      password: 123456
      timeout: 10000
      database: 0
      username: ming
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
knife4j:
  enable: true
  path: /doc.html
server:
  port: 3002
jwt:
  token: YWFhYmJiY2NjZGRkZWVlZmZmMTIzNDU2Nzg5MGFiY2RlZmdo
  mail:
    username: mingtops@163.com
    password: EPjGi3BEMQNFtxqu
    host: smtp.163.com

storage:
  endpoint: ${STORAGE_ENDPOINT:http://123.56.138.127:9000}
  accessKey: jmZSBVR3PW090c5o4Cnh
  secretKey: pqRPIsZKy7938B2LeG6wrbSHCFh5WxOjun4kTMOD
  bucket: ${STORAGE_BUCKET:avatars}
  region: ${STORAGE_REGION:us-east-1}
