spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 123.56.138.127:8848
        namespace: public
        group: DEFAULT_GROUP
        username: nacos
        password: VxykvMqce3
      config:
        username: nacos
        password: VxykvMqce3
    gateway:
      server:
        webflux:
          routes:
            - id: user
              uri: lb://User-Management
              predicates:
                - Path=/api/user/**
            - id: activity
              uri: lb://Activity-Management
              predicates:
                - Path=/api/activity/**
            - id: activities
              uri: lb://Activity-Management
              predicates:
                - Path=/api/activities/**

server:
  port: 3000

jwt:
  token: YWFhYmJiY2NjZGRkZWVlZmZmMTIzNDU2Nzg5MGFiY2RlZmdo
