spring:
  application:
    name: Activity-Management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activity?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 126824
  data:
    redis:
      host: 123.56.138.127
      port: 6379
      password: 123456
      timeout: 10000
      database: 0
      username: ming
  elasticsearch:
    uris: 123.56.138.127:9200
    username: ming
    password: 123456
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  rabbitmq:
    host: 123.56.138.127
    port: 5672
    username: ming
    password: 123456
    virtual-host: /
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
logging:
  level:
    com.example.activity.feign.ServiceFeign: DEBUG
    feign.Logger: DEBUG

jwt:
  token: YWFhYmJiY2NjZGRkZWVlZmZmMTIzNDU2Nzg5MGFiY2RlZmdo
longcat:
  api:
    key: ak_1Uk5ha1Tb3tI7iy3li4hS4Ek35G7l
ip2region:
  xdb:
    path: ${IP2R_XDB_PATH:}
    classpath: ${IP2R_XDB_CLASSPATH:ip2region_v4.xdb}
feign:
  client:
    config:
      longcat-chat:
        url: https://api.longcat.chat
        loggerLevel: FULL
        connectTimeout: 5000
        readTimeout: 30000

storage:
  endpoint: ${STORAGE_ENDPOINT:http://123.56.138.127:9000}
  accessKey: rustfsadmin
  secretKey: rustfsadmin
  bucket: ${STORAGE_BUCKET:activity-photos}
  region: ${STORAGE_REGION:us-east-1}

