spring:
  application:
    name: Activity-Comments-Likes
  datasource:
    url: jdbc:mysql://localhost:3306/luntan?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 126824
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 123.56.138.127
    port: 5672
    username: ming
    password: 123456
    virtual-host: /
  cloud:
    nacos:
      server-addr: 123.56.138.127:8848
      discovery:
        group: DEFAULT_GROUP
        namespace: public
  elasticsearch:
    uris: 123.56.138.127:9200
    username: ming
    password: 123456
#server:
#  port: 3003
